version: '2'
services:
  bot:
    command: ["sh", "./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_test.py"]
    environment:
      - PYTHONUNBUFFERED=0
      - SELENIUM=selenium
    build: bot
    depends_on:
      - selenium
      - web
    links:
      - selenium:selenium
      - web:web
    volumes:
      - ./bot:/bot

  web:
    build: .
    volumes:
      - .:/app
#    ports:
#      - "5000:5000"
    environment:
      - FLASK_ENV=development

  selenium:
    image: selenium/standalone-chrome:3.7
    environment:
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    ports:
      - "4444:4444"
#      - "5900:5900"
    shm_size: 128M
